### ISSUE TITLE
Use double quotes in title and description

### ISSUE THREAD

**Issue by ravnx** [nantipov/wordhugopress#10]
Using single quotes around title and description results in "failed to unmarshal YAML: yaml: did not find expected key"

title: 'The World's Largest R/C Car'
description: 'The World's Largest R/C Car'

If I manually edit each file and change to surround in double quotes it works.

**Comment by nantipov** [comment]
Hello @ravnx ,
Thank you for posting an issue.

Could you please provide more details?
1. Mentioned attributes are part of your original WordPress posts? Or those are the part of the `ftl` template file (`/src/main/resources/templates/empty-post.ftl`)?
2. a. Do single quotes exist originally in your WordPress post?
    b. Or do you want bring them during migration (e.g. you want to have single quotes around)?


#### 2a
If we are talking about case **2a**, you can remove quotes which are already presented in your local template file (`/src/main/resources/templates/empty-post.ftl`).
```yaml
...
---
title: '${post.title}'
...
description: '${post.title}'
...
```

=(remove quotes)>

```yaml
...
---
title: ${post.title}
...
description: ${post.title}
...
```

#### 2b
For the case of **2b**, please put additional doubled single quotes in your local template file (`/src/main/resources/templates/empty-post.ftl`).
```yaml
...
---
title: '${post.title}'
...
description: '${post.title}'
...
```

=(double the single quotes)>

```yaml
...
---
title: '''${post.title}'''
...
description: '''${post.title}'''
...
```

You may consider this as a workaround. Meanwhile, I have created a ticket for addressing this in the scaleable way (#11).

**Comment by nantipov** [comment]
Please let me know if this works for you.
Thank you.

**Comment by ravnx** [comment]
Thanks for the update. 
Yes I have a lot of posts with a title like: 'It's a Boy' or 'She's got me'
So when I run hugo, it errors out because from the import, it has three quotes. 
Let me try the template change for 2b.

Nope, I get:
`content/posts/80s-lyrics-quiz/index.md failed to unmarshal YAML: yaml: did not find expected key`
```
title: '''80's Lyrics Quiz'''
author: mp
date: 2003-11-03T16:05:08Z
publishdate: 2003-11-03T16:05:08Z
lastmod: 2003-11-03T16:05:08Z
draft: false
description: '''80's Lyrics Quiz'''
```

Let me try with double quotes, instead of escaped quotes:
Okay! That works, except, I have one post with the title: "Developer "Feedback""
So, that produces an error too, but, it's the only post out of 450, so, I just manually edited, the other way I have about 35 posts with single quotes in the title.

New template - src/main/resources/templates/empty-post.ftl
```
title: "${post.title}"
author: ${post.author}
date: ${post.createdAt?iso_local}
publishdate: ${post.createdAt?iso_local}
lastmod: ${post.modifiedAt?iso_local}
draft: ${post.draft?string("true", "false")}
description: "${post.title}"
```

Helps, but not a real "fix" for the future. Thank you for your time!

**Comment by nantipov** [comment]
Thanks for the update.
Yes, sure, definitely it is not a real fix. I have already created a ticket for handling the edge-cases around chars which have to be escaped in a right way.
