### ISSUE TITLE
Configuaration

### ISSUE THREAD

**Issue by g7uvw** [nantipov/wordhugopress#8]
Hi, I'm probably being dense, but I can't see where the configuration file is supposed to live or what it should be called. Can anyone enlighten me?

**Comment by nantipov** [comment]
Hi @g7uvw , thanks for interest in this project and sorry for confusion with the configuration file.

Well, this does not look very professional, but was implemented in a quick manner as a regular Spring `application.yaml` file.

Some time ago I created an issue #7 to address this.

Nevertheless, now, you can simply overwrite (or redefine) configuration file within project (`src/main/resources/application.yaml`) and then rebuild/run it (`./gradlew clean build run`).

Once #7 is implemented, this will be cleaner solution.

**Comment by g7uvw** [comment]
Thank you - I really wasn't sure where to look.

**Comment by nantipov** [comment]
Closed as refers to the existing issue #7 .
Clarification notes were added into `README.md` file.
